//
//  ApiKey.swift
//  GZ
//
//  Created by Денис on 04.05.2022.
//

import Foundation

let key = "eyJhbGciOiJIUzI1NiJ9.eyJhcGlfa2V5IjoiODhiZjI4OWNhNTQxYWQxOCIsInNjb3BlcyI6WyJwdXJjaGFzZXMiLCJwbGFuZ3JhcGhzMjAyMCJdLCJpYXQiOjE2NTE5MDYzMjQsImV4cCI6MTY1MTk5MjcyNCwiaXNzIjoiaHR0cHM6Ly9kZXYuZ29zcGxhbi5pbmZvIiwiYXVkIjoiaHR0cHM6Ly9nb3NwbGFuLmluZm8vYXBpL3YxIiwianRpIjoiYTU5MzE0OTctMjU4NC00YmEzLWIzZDMtMjVkNDNjYzFmMjU5In0._r0BAVQwwWdeGCHXiitv3xudGjg3koCttnBvPOXsD2U"
