//
//  ApiKey.swift
//  GZ
//
//  Created by Денис on 04.05.2022.
//

import Foundation

let key = "eyJhbGciOiJIUzI1NiJ9.eyJhcGlfa2V5IjoiODhiZjI4OWNhNTQxYWQxOCIsInNjb3BlcyI6WyJwdXJjaGFzZXMiLCJwbGFuZ3JhcGhzMjAyMCJdLCJpYXQiOjE2NTE5MTQ4MDUsImV4cCI6MTY1MjAwMTIwNSwiaXNzIjoiaHR0cHM6Ly9kZXYuZ29zcGxhbi5pbmZvIiwiYXVkIjoiaHR0cHM6Ly9nb3NwbGFuLmluZm8vYXBpL3YxIiwianRpIjoiNGQxZGQ5OTktNzRhNy00YTNkLWE0YmUtZTBiMDExOTYwN2Y2In0.voCkSKLc_GmfcgBjLpOALDs7tPSLoBkDBrAmZlImIQk"
